# Generated by Django 5.1.4 on 2024-12-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0003_menulink_site_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulink',
            name='favicont',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='assets/favicon/%Y/%m/'),
        ),
    ]
