# Generated by Django 5.1.4 on 2024-12-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_menulink_favicont'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulink',
            name='favicont',
        ),
        migrations.AddField(
            model_name='menulink',
            name='favicon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='assets/favicon/%Y/%m/'),
        ),
    ]
