# Generated by Django 5.1.4 on 2024-12-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0005_remove_menulink_favicont_menulink_favicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulink',
            name='favicon',
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='assets/favicon/%Y/%m/'),
        ),
    ]
