# Generated by Django 5.1.4 on 2024-12-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog12', '0003_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
