# Generated by Django 5.1.4 on 2024-12-13 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog12', '0004_page_content_page_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False, help_text='este campo deveraestar marcado para a paginaser exibido publicamente'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField(blank=True, max_length=1500, null=True)),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('is_published', models.BooleanField(default=False, help_text='este campo deveraestar marcado para o postser publicado')),
                ('content', models.TextField(blank=True, max_length=1500, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/')),
                ('cover_in_post_contente', models.BooleanField(default=False, help_text=' Exibir a imagem de capa tambem dentro do conteudo do post?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog12.category')),
                ('tag', models.ManyToManyField(blank=True, default='', to='Blog12.tag')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
